# Generated by Django 6.1 on 2026-08-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='max_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vacancies',
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
